### ISSUE TITLE
Fix missing evidence from form to table - specific workflow issue

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#63]
Hi @tmushayahama 

Li from MGI has reported a bug wrt evidence not populating the table when entered into the form, but for a specific case when there is an unpopulated field in the form.

How this arose:
The curator was using the CC only version of the form and entered a gp and a CC.  They then accidentally selected the 'Organism' extension when they meant to select 'Cell'. 

Since, right now, we don't have a line-by-line delete option in the form (or an undo action), the curator options are to either 'Clear' and start over or just select 'Cell' from the extension menu, leaving 'Organism' in the form but blank.

The curator chose the latter option, filled in the 'Cell' extension and then clicked on add 'Anatomy' and entered an anatomy term and evidence.

Once the annotation was saved, it appeared on the form, but the evidence code and reference for the 'Anatomy' extension was not there.  The curator had to add that evidence and reference again from the side 'Add evidence' option.

In trying to replicate this, I've also had the evidence disappear from the 'Cell' but stay with the 'Anatomy' term.

Here's a screenshot of what this looks like in the table:

![image](https://user-images.githubusercontent.com/1730534/73686234-9ad5dd80-4695-11ea-9146-4399b3b5d3ac.png)

Note the evidence code and reference missing for the 'oocyte' annotation.

@tmushayahama - let me know if you want to talk and share a screen to troubleshoot.

**Comment by vanaukenk** [comment]
@tmushayahama - let me know when there is something on noctua-dev to test.  Thx.

**Comment by tmushayahama** [comment]
@vanaukenk This was fixed or no longer occurring

**Comment by vanaukenk** [comment]
This is still an issue on the Noctua form 2.0.
@tmushayahama let's look at this together.
